<?php
/**
 * Mageinn_Hint extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Mageinn
 * @package     Mageinn_Hint
 * @copyright   Copyright (c) 2014 Mageinn. (http://mageinn.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */


/**
 * @category   Mageinn
 * @package    Mageinn_Hint
 * @author     Mageinn
 */
?>
<script type="text/javascript">
//<![CDATA[
if (typeof $j == 'undefined') { 
    $j = jQuery;
}

var optionHints = <?php echo $this->getOptionHints(); ?>;

function initHints(){
    $j('#product_options_container .option-box').each(function () {
        var id = $j(this).attr('id').replace("option_", "");
        var hint = '';
        if(optionHints[id] !== undefined) {
            hint = optionHints[id];
        }
        if($j('#hint_option_' + id).length == 0) {
            $j(this).append( '<div id="hint_option_' + id + '"><strong>Hint</strong> <br /><textarea class="hintMceEditor" \n\
cols="99" rows="2" style="height: 6em;" name="product[options][' + id + '][option_hint]" id="product_option_' + id + '_option_hint">' + hint + '</textarea></div>');
        }
    });
}

Event.observe('add_new_defined_option', 'click', function(event) {
    initHints();
});
initHints();
//]]>
</script>